name: Run Stack Analyser
author: Specfy
description: |-
  Run Specfy's Stack Analyser and send update to Specfy API


runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'box'
  color: 'white'
