import './browserstack';
import './circleci';
import './cypressci';
import './dependabot';
import './githubactions';
import './relativeci';
import './renovate';
import './teamcity';
import './travisci';
