import './dieselrs.js';
import './doctrinephp.js';
import './goent.js';
import './gorm.js';
import './kysely.js';
import './prisma.js';
import './sequelize.js';
import './sqlalchemy.js';
import './typeorm.js';
