import path from 'node:path';

import { describe, it, expect } from 'vitest';

import { FSProvider } from '../provider/fs';

import { techAnalyser } from '.';

describe('techAnalyser', () => {
  it('should run correctly', async () => {
    const res = await techAnalyser({
      provider: new FSProvider({
        path: path.join(__dirname, '../../../specfy'),
        ignorePaths: [],
      }),
    });

    expect(res.toJson()).toStrictEqual({
      name: 'main',
      type: 'project',
      path: '/',
      tech: null,
      inComponent: null,
      edges: [],
      components: [
        {
          name: 'db',
          type: 'component',
          edges: [],
          languages: {},
          path: '/docker-compose.yml',
          tech: 'postgresql',
          techs: [],
          inComponent: null,
        },
        {
          edges: [],
          name: 'api',
          type: 'component',
          path: '/pkgs/api',
          tech: null,
          inComponent: null,
          languages: {
            JSON: 3,
            Markdown: 1,
            Prisma: 1,
            TypeScript: 186,
            XML: 1,
          },
          techs: ['fastify', 'nodejs', 'prisma', 'typescript'],
        },
        {
          edges: [],
          name: 'app',
          type: 'component',
          path: '/pkgs/app',
          inComponent: expect.any(String),
          tech: null,
          languages: {
            HTML: 1,
            JSON: 5,
            SCSS: 79,
            TypeScript: 234,
          },
          techs: [
            'html',
            'nodejs',
            'react',
            'scss',
            'typescript',
            'vercel',
            'vite',
          ],
        },
        {
          edges: [],
          name: 'website',
          type: 'component',
          path: '/pkgs/website',
          inComponent: expect.any(String),
          tech: null,
          languages: {
            CSS: 1,
            HTML: 1,
            JSON: 3,
            JavaScript: 2,
            SCSS: 1,
            TypeScript: 7,
          },
          techs: [
            'css',
            'html',
            'javascript',
            'nodejs',
            'react',
            'scss',
            'tailwind',
            'typescript',
            'vercel',
            'vite',
          ],
        },
        {
          edges: [],
          name: 'rfc-editor',
          type: 'component',
          path: '/',
          inComponent: expect.any(String), // TODO: fix this inheritance issue
          tech: null,
          languages: {
            CSS: 1,
            HCL: 31,
            HTML: 2,
            JSON: 17,
            JavaScript: 4,
            Markdown: 2,
            Prisma: 1,
            SCSS: 80,
            Shell: 3,
            TypeScript: 427,
            XML: 1,
            YAML: 2,
          },
          techs: [
            'css',
            'docker',
            'eslint',
            'fastify',
            'github',
            'githubactions',
            'html',
            'javascript',
            'nodejs',
            'prettier',
            'prisma',
            'react',
            'scss',
            'shell',
            'stylelint',
            'tailwind',
            'terraform',
            'typescript',
            'vercel',
            'vite',
          ],
        },
        {
          name: 'vercel',
          type: 'hosting',
          languages: {},
          edges: [],
          path: '',
          tech: 'vercel',
          inComponent: null,
          techs: [],
        },
      ],
      techs: [
        'css',
        'docker',
        'eslint',
        'fastify',
        'github',
        'githubactions',
        'html',
        'javascript',
        'nodejs',
        'postgresql',
        'prettier',
        'prisma',
        'react',
        'scss',
        'shell',
        'stylelint',
        'tailwind',
        'terraform',
        'typescript',
        'vercel',
        'vite',
      ],
      languages: {
        CSS: 1,
        HCL: 31,
        HTML: 2,
        JSON: 17,
        JavaScript: 4,
        Markdown: 2,
        Prisma: 1,
        SCSS: 80,
        Shell: 3,
        TypeScript: 427,
        XML: 1,
        YAML: 2,
      },
    });
  });
});
