import type { AllowedKeys, TechItem } from '../types/techs';

export const list: TechItem[] = [
  { key: 'algolia', name: 'Algolia', type: 'db' },
  { key: 'alibabacloud', name: 'Alibaba Cloud', type: 'hosting' },
  { key: 'angular', name: 'Angular', type: 'language' },
  { key: 'aws', name: 'AWS', type: 'hosting' },
  { key: 'azure', name: 'Azure', type: 'hosting' },
  { key: 'bash', name: 'Bash', type: 'language' },
  { key: 'bootstrap', name: 'Bootstrap', type: 'tool' },
  { key: 'c', name: 'C', type: 'language' },
  { key: 'cplusplus', name: 'C++', type: 'language' },
  { key: 'csharp', name: 'C#', type: 'language' },
  { key: 'css', name: 'CSS', type: 'language' },
  { key: 'dart', name: 'Dart', type: 'language' },
  { key: 'datadog', name: 'Datadog', type: 'sass' },
  { key: 'digitalocean', name: 'Digital Ocean', type: 'hosting' },
  { key: 'docker', name: 'Docker', type: 'tool' },
  { key: 'elasticloud', name: 'Elastic Cloud', type: 'sass' },
  { key: 'elasticsearch', name: 'Elasticsearch', type: 'db' },
  { key: 'elixir', name: 'Elixir', type: 'language' },
  { key: 'eslint', name: 'Eslint', type: 'tool' },
  { key: 'express', name: 'Express', type: 'tool' },
  { key: 'fastify', name: 'Fastify', type: 'tool' },
  { key: 'gce', name: 'GCE', type: 'hosting' },
  { key: 'gcp', name: 'GCP', type: 'hosting' },
  { key: 'github', name: 'Github', type: 'sass' },
  { key: 'golang', name: 'Go', type: 'language' },
  { key: 'html', name: 'HTML', type: 'language' },
  { key: 'java', name: 'Java', type: 'language' },
  { key: 'jest', name: 'Jest', type: 'tool' },
  { key: 'jira', name: 'Jira', type: 'sass' },
  { key: 'kotlin', name: 'Kotlin', type: 'language' },
  { key: 'kubernetes', name: 'Kubernetes', type: 'hosting' },
  { key: 'mailchimp', name: 'Mailchimp', type: 'sass' },
  { key: 'mailjet', name: 'Mailjet', type: 'sass' },
  { key: 'mongodb', name: 'MongoDB', type: 'db' },
  { key: 'mysql', name: 'Mysql', type: 'db' },
  { key: 'netlify', name: 'Netlify', type: 'hosting' },
  { key: 'newrelic', name: 'New Relic', type: 'sass' },
  { key: 'nodejs', name: 'NodeJS', type: 'language' },
  { key: 'oraclecloud', name: 'Oracle Cloud', type: 'hosting' },
  { key: 'ovh', name: 'OVH', type: 'hosting' },
  { key: 'php', name: 'PHP', type: 'language' },
  { key: 'pingdom', name: 'Pingdom', type: 'sass' },
  { key: 'postgresql', name: 'Postgresql', type: 'db' },
  { key: 'powershell', name: 'Powershell', type: 'language' },
  { key: 'prettier', name: 'Prettier', type: 'tool' },
  { key: 'prisma', name: 'Prisma', type: 'tool' },
  { key: 'pubsub', name: 'PubSub', type: 'messaging' },
  { key: 'python', name: 'Python', type: 'language' },
  { key: 'rabbitmq', name: 'RabbitMQ', type: 'messaging' },
  { key: 'react', name: 'React', type: 'language' },
  { key: 'redis', name: 'Redis', type: 'db' },
  { key: 'ruby', name: 'Ruby', type: 'language' },
  { key: 'rust', name: 'Rust', type: 'language' },
  { key: 'sentry', name: 'Sentry', type: 'sass' },
  { key: 'slack', name: 'Slack', type: 'sass' },
  { key: 'sequelize', name: 'Sequelize', type: 'tool' },
  { key: 'sqreen', name: 'Sqreen', type: 'sass' },
  { key: 'stylelint', name: 'Styelint', type: 'tool' },
  { key: 'swift', name: 'Swift', type: 'language' },
  { key: 'tailwind', name: 'Tailwind', type: 'tool' },
  { key: 'terraform', name: 'Terraform', type: 'tool' },
  { key: 'typescript', name: 'Typescript', type: 'language' },
  { key: 'vercel', name: 'Vercel', type: 'hosting' },
  { key: 'vite', name: 'Vite', type: 'tool' },
  { key: 'vue', name: 'Vue', type: 'language' },
  { key: 'webpack', name: 'Webpack', type: 'tool' },
  { key: 'zapier', name: 'Zapier', type: 'sass' },
  { key: 'zoom', name: 'Zoom', type: 'sass' },
];

export const listIndexed: Record<AllowedKeys, TechItem> = {} as any;
Object.values(list).forEach((v) => {
  listIndexed[v.key] = v;
});
