import { register } from '../../register.js';

register({
  tech: 'sentry',
  name: 'Sentry',
  type: 'monitoring',
  dotenv: ['SENTRY_'],
  dependencies: [
    { type: 'docker', name: 'sentry' },
    { type: 'docker', name: 'getsentry/sentry' },
    { type: 'docker', name: 'getsentry/sentry-cli' },
    { type: 'docker', name: 'sentryintegrations/sentry-github-action-release' },
    { type: 'docker', name: 'daprio/sentry' },
    { type: 'docker', name: 'us.gcr.io/sentryio/sentry' },
    { type: 'npm', name: '@sentry/browser' },
    { type: 'npm', name: '@sentry/core' },
    { type: 'npm', name: '@sentry/node' },
    { type: 'npm', name: '@sentry/react' },
    { type: 'npm', name: '@sentry/minimal' },
    { type: 'npm', name: '@sentry/integrations' },
    { type: 'rust', name: 'sentry' },
    { type: 'ruby', name: 'sentry-ruby' },
    { type: 'ruby', name: 'sentry-rails' },
    { type: 'php', name: 'sentry/sentry' },
    { type: 'php', name: 'sentry/sentry-symfony' },
    { type: 'php', name: 'sentry/sentry-laravel' },
    { type: 'php', name: 'sentry/sdk' },
    { type: 'githubAction', name: 'getsentry/action-release' },
    { type: 'golang', name: 'github.com/getsentry/sentry-go' },
    { type: 'python', name: 'sentry_sdk' },
  ],
});
