import './biomejs.js';
import './eslint.js';
import './golangcilint.js';
import './phpstan.js';
import './prettier.js';
import './rubocop.js';
import './sonarlint.js';
import './stylelint.js';
import './vale.js';
